#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<string.h>

#define STARTING_CASH 1500
#define STARTING_LOAN 4000
#define AMOUNT_DAYS 15

/*
 Description: generates random number within a range inclusive of the upper and lower limits
 			  this function also utilizes rand() which is constantly getting reseeded to time
 			  in main() which makes the number generated by rand() more random

 Parameters:
 	int nLower	the lower limit of the range of values
 	int nUpper	the upper limit of the range of values
 :
 Return value: int, the random number the function has generated within the range
*/
int getRandom(int nLower, int nUpper)
{
	int nRandom;
	int nIncUpper; //inclusive upper

	nIncUpper = nUpper + 1;
	nRandom = rand() % (nIncUpper - nLower);


	nRandom += nLower;


	return nRandom;
}
/*
 Description: Returns the max amount of oils player can sell (which is current player stock)
 		      and displays a message informing the user the max amount of oils they can sell, if any
 Parameters:
 	int nSellChoice	 stores the sell choice the oil the user wishes to sell
 	LEGEND: 1- Rosemary
 			2- Lavender
 			3- Lemon
 			4- Mint
 			5- Clear Minds
 			6- Energy Booster
 			7- Calming

 	int nOilSellPrice	the sell price of the chosen oil in bottles, divided by 10 in the function to get
	 					 sell price per drop
 	int	nPlayerStock	the current stock of the chosen oil in drops if EO, bottles if DO


 Return value: returns int nPlayerStock to nMaxSellAmt which will be used in getSellAmt
 				to verify if user is entering a valid amount

*/
int get_display_MaxOilSell(int nSellChoice, int nOilSellPrice, int nPlayerStock)
{
	if(nSellChoice == 1)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Rosemary in stock, please enter 0 to go back to the main menu: ");
		}
		else
		{
			printf("\nYou can sell %d Rosemary drops for %d.", nPlayerStock, nPlayerStock * (nOilSellPrice / 10));

		}

		return nPlayerStock;
	}
	else if(nSellChoice == 2)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Lavender in stock, please enter 0 to go back to the main menu: ");
		}
		else
		{
			printf("\nYou can sell %d Lavender drops for %d.", nPlayerStock, nPlayerStock * (nOilSellPrice / 10));

		}

		return nPlayerStock;
	}
	else if (nSellChoice == 3)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Lemon in stock, please enter 0 to go back to the main menu: ");
		}
		else
		{

			printf("\nYou can sell %d Lemon drops for %d.", nPlayerStock, nPlayerStock * (nOilSellPrice / 10));
		}
		return nPlayerStock;
	}
	else if (nSellChoice == 4)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Mint in stock, please enter 0 to go back to the main menu: ");

		}
		else
		{

			printf("\nYou can sell %d Mint drops for %d.", nPlayerStock, nPlayerStock * (nOilSellPrice / 10));
		}
		return nPlayerStock;
	}
	else if(nSellChoice == 5)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Clear Minds in stock, please enter 0 to go back to the main menu: ");

		}
		else
		{
			printf("\nYou can sell %d Clear Minds bottles for %d.", nPlayerStock, nPlayerStock * nOilSellPrice);

		}

		return nPlayerStock;

	}
	else if(nSellChoice == 6)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Energy Booster in stock, please enter 0 to go back to the main menu: ");

		}
		else
		{

			printf("\nYou can sell %d Energy Booster bottles for %d.", nPlayerStock, nPlayerStock * nOilSellPrice);
		}

		return nPlayerStock;
	}
	else if(nSellChoice == 7)
	{
		if(nPlayerStock == 0)
		{
			printf("You have no Calming in stock, please enter 0 to go back to the main menu: ");

		}
		else
		{

			printf("\nYou can sell %d Calming bottles for %d.", nPlayerStock, nPlayerStock * nOilSellPrice);
		}
		return nPlayerStock;
	}

}
/*

 Description: asks user to input amount of oils they want to sell, only accepts valid input
 Parameters:

 int nMaxSellAmt	current stock of the chosen oil

 :
 Return value: int nSellAmt, a valid amount the user wishes to sell
*/

int getSellAmt(int nMaxSellAmt)
{
	int bValidSellAmt, nSellAmt;

	bValidSellAmt = 0;

	if(nMaxSellAmt != 0)
	{
		printf("\nHow many drops of this essential oil would you like to sell?\n");

	}

	while(bValidSellAmt == 0)
	{
		scanf("%d", &nSellAmt);

		if(nSellAmt <= nMaxSellAmt && nSellAmt >= 0)
		{
			bValidSellAmt = 1;
		}
		if(bValidSellAmt == 0)
		{
			printf("Please enter only a valid amount to sell. ");
		}
	}

	return nSellAmt;
}
/*
 Description: displays the cities the player can travel to and corresponding int values
 they have to enter
 Parameters:
 	none, input is taken in the function startDay
 :
 Return value: none
*/

void displayCityChoices()
{
	printf("\n\n\nTravel to which city?\n");
	printf("<><><><><><><><><>\n");
	printf("<>||[1] Manila||<>\n");
	printf("<>||[2] Makati||<>\n");
	printf("<>||[3]Alabang||<>\n");
	printf("<>||[4] Quezon||<>\n");
	printf("<>||||| City  ||<>\n");
	printf("<><><><><><><><><>\n");
	printf("Number of city of choice: ");
}
/*
 Description: displays the city depending on current city player is in
 Parameters:
		int* nCity	used to determine which city to display

 CITIES LEGEND : 1- Manila, 2- Makati, 3- Alabang, 4- Quezon City
 Return value: none
*/
void displayCity(int nCity)
{
	switch(nCity)
		{
			case 1:
				printf("|| Current City: Manila\n");
				break;
			case 2:
				printf("|| Current City: Makati\n");
				break;
			case 3:
				printf("|| Current City: Alabang\n");
				break;
			case 4:
				printf("|| Current City: Quezon City\n");
				break;
			default:
				printf("Not a valid city\n");

		}
}
/*
Description: compute for the selling price of calming for the day per unit

Parameters:
	int nLemonSellPrice	  sell price of lemon in current city per bottle
	int nLavenderSellPrice	sell price of lavender in current city per bottle
	int nRosemaryPrice 		sell price of rosemary in current city per bottle

Return value: int, sell price of calming per bottle
*/
int computeCalmingPrice(int nLemonSellPrice, int nLavenderSellPrice, int nRosemarySellPrice)
{
	return 1.15 * (3 * (nLavenderSellPrice / 10) + 2 * (nRosemarySellPrice / 10) + nLemonSellPrice / 10);
}
/*
Description: computes for the selling price of energy booster for the day per unit

Parameters:
	int nLemonSellPrice	  sell price of lemon in current city per bottle
	int nMintSellPrice	sell price of lavender in current city per bottle
	int nRosemarySellPrice 		sell price of rosemary in current city per bottle



Return value: int, selling price of energy booster per bottle

 */

int computeEBPrice(int nLemonSellPrice, int nRosemarySellPrice, int nMintSellPrice)
{
	return 1.15 * (nLemonSellPrice / 10 + nRosemarySellPrice / 10 + nMintSellPrice / 10);
}
/*
Description: computes for the selling price of clear minds for the day per unit

Parameters:
	int nLemonSellPrice	  sell price of lemon in current city per bottle
	int nMintSellPrice	sell price of lavender in current city per bottle
	int nRosemarySellPrice 		sell price of rosemary in current city per bottle


Return value: int, selling price of CM per bottle

 */
int computeCMPrice(int nLemonSellPrice, int nRosemarySellPrice, int nMintSellPrice)
{
	return  1.15 * (3 * (nLemonSellPrice / 10) + 2 * (nRosemarySellPrice / 10) + 2 * (nMintSellPrice / 10));
}
/*
Description: resets values so that the player may choose to buy again with different values and oils

Parameters:
	int* nBuyPrice		price of essential oil chosen
	int* nCurrentStock	stock in bottles of chosen essential oil
	int*  nMaxBuyAmt	max amount of bottles player can buy

Return value: none

 */
void resetBuyValues(int* nBuyPrice, int* nCurrentStock, int* nMaxBuyAmt)
{
	*nBuyPrice = 0;
	*nCurrentStock = 0;
	*nMaxBuyAmt = 0;

}

/*
 Description: shows the options player can choose in the start
 Parameters:
 	none

 Return value: none
*/
void displayStartMenu()
{
	printf("\nWELCOME TO OILBULARYO ON THE GO!\n");
    printf("\n[1]Start a Sales Trip");
    printf("\n[2]View Top Ten List");
    printf("\n[3]Exit Game\n\n");
    printf("Please enter the number that corresponds with your choice: ");

}
/*
 Description: asks user for a number that corresponds to the chosen essential oil
 			  they wish to buy and makes sure the user enters a valid input
 Parameters:
 	none

 Return value: int nEOChoice, number that represents players chosen oil
*/
int getEOChoice()
{
	int bValidEO;
	int nEOChoice;

	bValidEO = 0;

	printf("Please enter the number of your choice: ");
	while(bValidEO == 0)
	{
		scanf("%d", &nEOChoice);
		if(nEOChoice >= 0 && nEOChoice <= 4)
		{
			bValidEO = 1;
		}
		if(bValidEO == 0)
		{
			printf("Please only enter a number from 0 to 4: ");
		}
	}
	return nEOChoice;
}
/*
 Description: assigns the appropriate buy price and stock per bottle to nBuyPrice and nCurrentStock
 				which will be used in computations and future functions in the process of buying essential oils
 Parameters:
 	int* nBuyPrice	will hold the chosen oil's price per bottle
 	int* nCurrentStock	will hold the chosen oil's stock in the current city
 	int	nOilShopPrice	price of chosen essential oil per bottle
 	int	nOilStock	stock of chosen oil in bottles


 Return value: none
*/

void setPriceAndStock(int* nBuyPrice, int* nCurrentStock, int nOilShopPrice, int nOilStock)
{
	*nBuyPrice = nOilShopPrice;
	*nCurrentStock = nOilStock;
}
/*
 Description: finds the max amount of essential oils the player can buy based on
 				the current stock of the city's oil dealer and the amount of cash the player has
 Parameters:
 	int nCash	the amount of cash player currently has
 	int	nBuyPrice	the buy price of the chosen essential oil
 	int nCurrentStock	the amount of bottles of chosen essential oil available to buy in the current city

 Return value: int nMaxBuyAmt, the maximum amount of bottles player can buy
*/

int computeMaxBuyAmt(int nCash, int nBuyPrice, int nCurrentStock)
{
	int nMaxBuyAmt;

	if(nCash >= nBuyPrice * nCurrentStock)
	{
		nMaxBuyAmt = nCurrentStock;
	}
	else
	{
		nMaxBuyAmt = nCash / nBuyPrice;
	}

	return nMaxBuyAmt;
}
/*
 Description: displays the number a player can enter based on their choice when buying essential oils

 Parameters: none

 Return value: none
*/

void displayEOChoices()
{
		printf("\nWhich essential oil would you like to buy?\n");
		printf("===========================\n");
    	printf("><><><><><><><><><><><><><>\n");
     	printf("|[1] Rosemary [2] Lavender|\n");
       	printf("|[3] Lemon    [4] Mint    |\n");
       	printf("><><><><><><><><><><><><><>\n");
        printf("===========================\n");
        printf("You may also enter [0] to exit.\n\n\n");
}
/*
 Description: asks user to enter a valid amount of chosen essential oil to buy based on
 			  nMaxBuyAmt computed beforehand
 Parameters:
 	nMaxBuyAmt	max amount of essential oils user can buy based on current stock and cash of player

 Return value: int nBuyAmt, the amount of chosen essential oil the user will buy
*/

int getBuyAmt(int nMaxBuyAmt)
{
	int bValidBuyAmt, nBuyAmt;
	bValidBuyAmt = 0;

	while(bValidBuyAmt == 0)
	{
		scanf("%d", &nBuyAmt);

		if(nBuyAmt >= 0 && nBuyAmt <= nMaxBuyAmt)
		{
			bValidBuyAmt = 1;
		}
		if(bValidBuyAmt == 0)
		{
			printf("Please only enter a valid amount: ");
		}

	}

	return nBuyAmt;
}
/*
 Description: computes for the new average price per drop everytime a user buys an essential oil
 Parameters:
 	int nOldStockEO	 user's stock of chosen essential oil before he will buy more of chosen essential oil
 	int nOldAveE   previous average price per drop
 	int nBuyAmt		amount of bottles of chosen essential oil the user will buy
 	int nEOShopPrice	current price of chosen essential oil per bottle


 Return value: int nAveDrop, computed new average cost per drop
*/
int computeAveDrop(int nOldStockEO, int nOldAveEO, int nBuyAmt, int nEOShopPrice)
{
	int nAveDrop;
	nAveDrop = (nOldStockEO * nOldAveEO + (nBuyAmt * 10) * (nEOShopPrice / 10) ) / (nOldStockEO + nBuyAmt * 10);

	return nAveDrop;
}
/*
 Description: requests user to enter a valid number of the oil they wish to sell
 Parameters:
 	none


 Return value: int nSellChoice, chosen oil the user wishes to sell
*/

int getSellChoice()
{
	int bValidSellChoice, nSellChoice;

	bValidSellChoice = 0;

	while(bValidSellChoice == 0)
	{
		scanf("%d", &nSellChoice);

		if(nSellChoice >= 0 && nSellChoice <= 7)
		{
			bValidSellChoice = 1;
		}
		if(bValidSellChoice == 0)
		{
			printf("Please enter a number from 1-7 only. Enter [0] if you wish to exit. \n");
		}
	}

	return nSellChoice;

}
/*
 Description: adds the amount of money player earned after selling chosen EO and updates player's stock on hand
 Parameters:
 	int* nCash	current cash of player
 	int* nPlayerStock	current stock of the chosen essential oil the player wishes to sell
 	int	nSellAmt	the amount of drops the user wishes to sell
 	int nOilSellPrice	selling price of chosen essential oil in current city

 Return value: none
*/

void sellEO(int* nCash, int* nPlayerStock, int nSellAmt, int nOilSellPrice)
{
	*nPlayerStock -= nSellAmt;
	*nCash += nOilSellPrice / 10 * nSellAmt;
}
/*
 Description: adds the amount of money player earned after selling chosen diffuser oil
 				and updates player's stock on hand
 Parameters:
 	int* nCash	current cash of player
 	int* nPlayerStock	current stock of the chosen diffuser oil the player wishes to sell
 	int	nSellAmt	the amount of bottles of chosen diffuser oil the player wishes to sell
 	int nOilSellPrice	selling price of chosen diffuser oil in current city

 Return value: none
*/

void sellDO(int* nCash, int* nPlayerStock, int nSellAmt, int nOilSellPrice)
{
	*nPlayerStock -= nSellAmt;
	*nCash += nOilSellPrice * nSellAmt;
}
/*
 Description: asks user to enter a valid  number that represents the user's chosen city to visit

  CITIES LEGEND : 1- Manila, 2- Makati, 3- Alabang, 4- Quezon City

 Parameters:
 	none
 Return value: int nCity, chosen city to visit
*/

int getCity()
{
	int bValidCity;
	int nCity;

	bValidCity = 0;

	while(bValidCity == 0)
	{
		scanf("%d",&nCity);
		if(nCity >= 1 && nCity <= 4)
		{
			bValidCity = 1;
		}

		if(bValidCity == 0)
	    {
			printf("Please enter a valid number: ");
		}
	}

	return nCity;
}
/*
 Description: computes for the final sell price based on the generated factors,
 		    	chance of factor being subtracted, multiplied, or added to base price,and base price

 Parameters:
 	int nFactor		the randomly generated factor within the range of the essential oil
 					which will be added, subtracted, or multiplied to the base price, sometimes
 					it's not used at all

 	int nChance		a number randomly generated from 1 to 100 that represents chance of base price
 					being multiplied, subtracted, or added to the factor. The base price also has a
 					chance of being retained.

 	int nBasePrice	generated base price of essential oil

 Return value: the final sell price of the oil for that day, returns 0 if the computed price
 				is negative or 0 which means oil is not available in that city
*/


int computeFinalPrice(int nFactor, int nChance, int nBasePrice)
{
	int nFinalShopPrice;

	if(nChance >= 1 && nChance <= 35)
	{
		nFinalShopPrice = nBasePrice + nFactor;
		return nFinalShopPrice;
	}
	else if(nChance >= 36 && nChance <= 70)
	{
		nFinalShopPrice = nBasePrice - nFactor;

		if(nFinalShopPrice <= 0)
		{
			return 0;
		}
		else
		{
			return nFinalShopPrice;
		}
	}
	else if(nChance >= 71 && nChance <= 90)
	{
		nFinalShopPrice = nBasePrice * nFactor;
		return nFinalShopPrice;
	}
	else if(nChance >= 91 && nChance <= 100)
	{
		nFinalShopPrice = nBasePrice;
		return nFinalShopPrice;
	}
}

/*
 Description: randomly generates amount of bottles in stock for the essential oil, returns 0 if the oil is
 			  not available in city. Otherwise, returns a random value from 5 to 20

 Parameters:
 	int	nFinalPrice	 the final selling price generated for the essential oil, 0 if the oil is unavailable

 Return value: int nStock, amount of stock of essential oil for the day
*/

int generateStock(int nFinalPrice)
{
	int nStock;

	if(nFinalPrice <= 0)
	{
		nStock = 0;
	}
	else
	{
		nStock = getRandom(5, 20);
	}

	return nStock;

}
/*
 Description: asks user to enter a number that represents the diffuser oil they would like to make, only
 			  pushes through with the process of selling diffuser oils if the user has enough money to afford
 			  the diffuser charge and enough ingredients to make at least one essential oil, requests user to
 			  enter 0 if a transaction can't push through to go back to the menu

 Parameters:
 	int nLemonP		amount of lemon player has in stock in drops
 	int nLavenderP	amount of Lavender player has in stock in drops
 	int nRosemaryP	amount of Rosemary player has in stock in drops
 	int nMintP		amount of Mint player has in stock in drops
 	int	 nDiffuserCharge	generated diffuser charge to make oils in the city for the day

 Return value: int nDOChoice, number that represents the diffuser oil the player wishes to make
 				1- Clear Minds, 2- Energy Booster, 3- Calming
*/

int getDOChoice(int nLemonP, int nLavenderP, int nRosemaryP, int nMintP, int nCash, int nDiffuserCharge)
{
	int nDOChoice;
	int bValidDO;

	bValidDO = 0;
    nDOChoice = 0;


    if(nCash < nDiffuserCharge)
	{
		printf("\nYou can't afford the processing plant fee, please enter 0 to go back to the main menu.\n");
	}

	printf("\nPlease enter the number that corresponds to your choice: ");

	while(bValidDO == 0)
	{
		scanf("%d", &nDOChoice);

		if(nDOChoice == 1 && nLemonP >= 3 && nRosemaryP >= 2 && nMintP >= 2 && nCash >= nDiffuserCharge)
		{
			bValidDO = 1;

		}
		else if(nDOChoice == 2 && nRosemaryP >= 1 && nMintP >= 1 && nLemonP >= 1 && nCash >= nDiffuserCharge)
		{
			bValidDO = 1;

		}
		else if(nDOChoice == 3 && nLavenderP >= 3 && nRosemaryP >= 2 && nLemonP >= 1 && nCash >= nDiffuserCharge)
		{
			bValidDO = 1;

		}
		else if(nDOChoice == 0)
		{
			bValidDO = 1;
		}



		if(bValidDO == 0)
		{
			printf("Invalid number, please only enter a number from choices being displayed: ");
		}

	}

	return nDOChoice;


}
/*
 Description: generates cost for making diffuser oils, range of random charge varies depending on city

 Parameters:
 	nCity	int that represents current city of player
 Return value: int nDiffuserCharge, charge for making diffuser oils in player's current city
*/
int generateDiffuserCharge(int nCity)
{
	int nDiffuserCharge;

	if(nCity == 1)//Manila
	{
		nDiffuserCharge = getRandom(20, 30);
	}
	else if(nCity == 2)//Makati
	{
		nDiffuserCharge = getRandom(80, 100);
	}
	else if(nCity == 3)//Alabang
	{
		nDiffuserCharge = getRandom(70, 90);
	}
	else if(nCity == 4)//Quezon
	{
		nDiffuserCharge = getRandom(40, 60);
	}

	return nDiffuserCharge;

}

/*
 Description: computes for the max amount of diffuser oils the player can make based on player's stock
 			  of essential oils and chosen diffuser oil, to be used to validate the amount of diffuser oils
 			  player wishes to make
 Parameters:
 	int nLemonP		current player stock of lemon in drops
 	int nLavenderP	current player stock of lavender in drops
 	int nRosemaryP	current player stock of rosemary in drops
 	int nMintP		current player stock of mint in drops
 	int nDOChoice	int that represents player's diffuser oil choice

 		1- Clear Minds, 2- Energy Booster, 3- Calming


 Return value: int nMaxDOAmt, the max amount of chosen diffuser oils player can make
*/
int computeMaxDOAmt(int nLemonP, int nLavenderP, int nRosemaryP, int nMintP, int nDOChoice)
{
	int nMaxDOAmt;

	nMaxDOAmt = 0;

	if(nDOChoice == 1)
	{
		while(nLemonP >= 3 && nRosemaryP >= 2 && nMintP >= 2)
		{
			nLemonP -= 3;
			nRosemaryP -= 2;
			nMintP -= 2;
			nMaxDOAmt++;
		}
	}
	else if(nDOChoice == 2)
	{
		while(nLemonP >= 1 && nRosemaryP >= 1 && nMintP >= 1)
		{
			nLemonP -= 1;
			nRosemaryP -= 1;
			nMintP -= 1;
			nMaxDOAmt++;
		}
	}
	else if(nDOChoice == 3)
	{
		while(nLavenderP >= 3 && nRosemaryP >= 2 && nLemonP >= 1)
		{
			nLavenderP -= 3;
			nRosemaryP -= 2;
			nLemonP -= 1;
			nMaxDOAmt++;
		}
	}

	return nMaxDOAmt;
}
/*
 Description: after user decides to make a certain amount of Clear Minds, this function
 			  updates player's essential oils stock on hand depending on amount of CLear Minds made
 Parameters:
 	int* nLemonP	amount of lemon drops player has in stock
 	int* nRosemaryP	amount of Rosemary drops player has in stock
 	int* nMintP		amount of Mint drops player has in stock
 	int nDOAmt		amount of Clear Minds player made

 Return value: none, updates essential oil count of player
*/

void makeCM(int* nLemonP, int* nRosemaryP, int* nMintP, int nDOAmt)
{
	int i;

	for(i = 0; i < nDOAmt; i++)
	{
		*nLemonP -= 3;
		*nRosemaryP -= 2;
		*nMintP -= 2;
	}
}
/*
 Description: after user decides to make a certain amount of Energy Booster, this function
 			  updates player's essential oils stock on hand depending on amount of Energy Booster made
 Parameters:
 	int* nLemonP	amount of lemon drops player has in stock
 	int* nRosemaryP	amount of Rosemary drops player has in stock
 	int* nMintP		amount of Mint drops player has in stock
 	int nDOAmt		amount of Clear Minds player made

 Return value: none, updates essential oil count of player
*/


void makeEB(int* nLemonP, int* nMintP, int* nRosemaryP, int nDOAmt)
{
	int i;

	for(i = 0; i < nDOAmt; i++)
	{
		*nLemonP -= 1;
		*nMintP -= 1;
		*nRosemaryP -= 1;
	}

}

/*
 Description: after user decides to make a certain amount of Calming, this function
 			  updates player's essential oils stock on hand depending on amount of Calming made
 Parameters:
 	int* nLemonP	amount of lemon drops player has in stock
 	int* nRosemaryP	amount of Rosemary drops player has in stock
 	int* nLavenderP		amount of Lavender drops player has in stock
 	int nDOAmt		amount of Clear Minds player made

 Return value: none, updates essential oil count of player
*/

void makeCalming(int* nLavenderP, int* nRosemaryP, int* nLemonP, int nDOAmt)
{
	int i;

	for(i = 0; i < nDOAmt; i++)
	{
		*nLavenderP -= 3;
		*nRosemaryP -= 2;
		*nLemonP -= 1;
	}
}

/*
 Description: takes user input, which will be the amount of diffuser oils the player wishes to make, until
 			  a valid amount of diffuser oils is entered based on the max amount of diffuser oils players
 			  can make generated beforehand
 Parameters:
 	int nMaxDOAmt	max amount of diffuser oils player can make with respect to player's current stock
 					of essential oils

 Return value: int nDOAmt, the amount of diffuser oils the player wishes to make
*/

int getDOAmt(int nMaxDOAmt)
{
	int nDOAmt;

	do
	{
		scanf("%d", &nDOAmt);

		if(nDOAmt > nMaxDOAmt || nDOAmt < 0)
		{
			printf("Please enter a valid amount of diffuser oils to make: ");
		}

	}while(nDOAmt > nMaxDOAmt || nDOAmt < 0);
}
/*
 Description: gets the amount of each essential oil used after the Clear Minds are made, used
 			  to calculate average diffuser price per bottle
 Parameters:
	int* nLemonUsed	  the amount of lemon drops used
	int* nRosemaryUsed	the amount of Rosemary drops used
	int* nMintUsed	the amount of mint drops used
	int nDOAmt	the amount of Clear Minds the user made


 Return value: none
*/

void getCMUsed(int* nLemonUsed, int* nRosemaryUsed, int* nMintUsed, int nDOAmt)
{
	int i;

	*nLemonUsed = 0;
	*nRosemaryUsed = 0;
	*nMintUsed = 0;

	for(i = 0; i < nDOAmt; i++)
	{
		*nLemonUsed += 3;
		*nRosemaryUsed += 2;
		*nMintUsed += 2;

	}
}
/*
 Description: gets the amount of each essential oil used after Energy Boosters are made, used
 			  to calculate average diffuser price per bottle
 Parameters:
	int* nLemonUsed	  the amount of lemon drops used
	int* nRosemaryUsed	the amount of Rosemary drops used
	int* nMintUsed	the amount of mint drops used
	int nDOAmt	the amount of Energy Booster the user made


 Return value: none
*/
void getEBUsed(int* nLemonUsed, int* nMintUsed, int* nRosemaryUsed, int nDOAmt)
{
	int i;

	*nLemonUsed = 0;
	*nMintUsed = 0;
	*nRosemaryUsed = 0;

	for(i = 0; i < nDOAmt; i++)
	{
		*nLemonUsed += 1;
		*nMintUsed += 1;
		*nRosemaryUsed += 1;
	}

}

/*
 Description: gets the amount of each essential oil used after user makes Caling are made, used
 			  to calculate average diffuser price per bottle
 Parameters:
	int* nLemonUsed	  the amount of lemon drops used
	int* nRosemaryUsed	the amount of Rosemary drops used
	int* nLavenderUsed	the amount of Lavender drops used
	int nDOAmt	the amount of Calming the user made


 Return value: none
*/

void getCalmingUsed(int* nLavenderUsed, int* nRosemaryUsed, int* nLemonUsed, int nDOAmt)
{
	int i;

	*nLavenderUsed = 0;
	*nRosemaryUsed = 0;
	*nLemonUsed = 0;

	for(i = 0; i < nDOAmt; i++)
	{
		*nLavenderUsed += 3;
		*nRosemaryUsed += 2;
		*nLemonUsed += 1;
	}
}
/*
 Description: when user chooses to pay debt, asks for the amount player would like to play until a valid
 			  amount is entered depending on the current loan of the player and the amount of cash the
 			  player currently has. If the player has already paid off their loans, they will be prompted to
 			  enter 0 to go back to the main menu
 Parameters:
 	int nCash	the amount of cash on hand the player currently has
 	int nLoan	the amount of debt the player has


 Return value: int nPayDebtAmt, the amount of debt the player would like to pay off
*/
int getPayDebtAmt(int nCash, int nLoan)
{
	int nPayDebtAmt;

	do
	{
		if(nLoan == 0)
		{
			printf("\nYou have no more debt to pay off, congrats! Please enter 0 to go back to the main menu. \n");
		}
		else
		{
			printf("\nPlease enter the amount you would like to pay off from your loans: ");

		}

		scanf("%d", &nPayDebtAmt);

	}while(nPayDebtAmt < 0 || nPayDebtAmt > nCash || nPayDebtAmt > nLoan);

	return nPayDebtAmt;

}
/*
 Description: gets the amount of cash the player would like to loan, cash and debt values are updated in main

 Parameters:
 	none

 Return value: int nLoanAmt, the amount of cash player would like to loan from loan shark
*/

int getLoanAmt()
{
	int nLoanAmt;

	do
	{
		printf("\nPlease enter the amount of money you would like to loan: ");
		scanf("%d", &nLoanAmt);

	}while(nLoanAmt < 0);

	return nLoanAmt;
}
/*
 Description: this function has a 40% chance of being used daily, if used it adds a bottle's worth of drops
 			  of a random essential oil (each oil has a 1 in 4 chance of being chosen) to the player's stock on
			   hand
 Parameters:
 	int* nLemonP	the stock of lemon drops player has
	int* nRosemaryP	the stock of Rosemary drops player has
 	int* nLavenderP	the stock of lavender drops player has
 	int* nMintP		the stock of mint drops player has

 Return value: none, updates player stock through pointers
*/
void getFreeEO(int* nLemonP, int* nRosemaryP, int* nLavenderP, int* nMintP)
{
	int nEO;

	nEO = getRandom(1, 100);

	if(nEO >= 1 && nEO <= 25)
	{
		*nLemonP += 10;
	}
	else if(nEO >= 26 && nEO <= 50)
	{
		*nRosemaryP += 10;
	}
	else if(nEO >= 51 && nEO <= 75)
	{
		*nLavenderP += 10;
	}
	else if(nEO >= 76 && nEO <= 100)
	{
		*nMintP += 10;
	}
}
/*
 Description: this function has a 30% chance of being used daily, if used it adds a bottle
 			  of a random diffuser oil (each oil has a 1 in 3 chance of being chosen) to the player's stock on
			   hand
 Parameters:
 	int* nCM	player's current stock of Clear Minds
 	int* nEB	player's current stock of Energy Booster
 	int* nCalming	player's current stock of Calming

 Return value: none, updates player stock through pointers
*/
void getFreeDO(int* nCM, int* nEB, int* nCalming)
{
	int nDO;

	nDO = getRandom(1, 12);

	if(nDO >= 1 && nDO <= 4)
	{
		*nCM += 1;
	}
	else if(nDO >= 5 && nDO <= 8)
	{
		*nEB += 1;

	}
	else if(nDO >= 9 && nDO <= 12)
	{
		*nCalming += 1;
	}

}
/*
 Description: swaps the values between two ints, this function is used to insert player's score into the top ten
 			  list, and is also used to adjust all the other scores in the top ten list accordingly

 Parameters:
 	int* nOne	the first int that will take the value of nTwo
 	int* nTwo 	the second int that will take the value of nOne

 Return value:none, values of ints are updated through pointers
*/
void swapNum(int* nOne, int* nTwo)
{
	int nTemp;

	nTemp = *nOne;
	*nOne = *nTwo;
	*nTwo = nTemp;
}

int main()
{
	/*set seed of rand() to time so that its repeatedly getting reseeded, rand() used in getRandom() for
	random number generation within ranges*/
	srand(time(0));

	int bShowMenu, nChoice;
	int nCash, nLoan, nDay, nCity;
	int nLemonP, nLavenderP, nRosemaryP, nMintP;
	int nCM, nEB, nCalming;

	int nLemonShop, nLavenderShop, nRosemaryShop, nMintShop;
	int nLemonStock, nLavenderStock, nRosemaryStock, nMintStock;
	int nCMPrice, nEBPrice, nCalmingPrice;
	int bRunMenu, nAction;
	int nEOChoice;
	int nBuyPrice, nBuyAmt, nMaxBuyAmt;
	int nCurrentStock;
	int nSellChoice, nSellAmt, nMaxSellAmt;

	int nAveLemon, nAveLavender, nAveRosemary, nAveMint;
	int nOldStockLemon, nOldStockLavender, nOldStockRosemary, nOldStockMint;
	int nOldAveLemon, nOldAveLavender, nOldAveRosemary, nOldAveMint;

	int nLemonBasePrice, nLavenderBasePrice, nRosemaryBasePrice, nMintBasePrice;
	int nLemonFactor, nLavenderFactor, nRosemaryFactor, nMintFactor;
	int nLemonChance, nLavenderChance, nRosemaryChance, nMintChance;

	int nLemonSellPrice, nLavenderSellPrice, nRosemarySellPrice, nMintSellPrice;
	int nDOChoice, nDiffuserCharge;
	int nMaxDOAmt, nDOAmt;

	int nAveCM, nAveEB, nAveCalming;
	int nLemonUsed, nLavenderUsed, nRosemaryUsed, nMintUsed;
	int nOldAveCM, nOldAveEB, nOldAveCalming;
	int nOldAmtCM, nOldAmtEB, nOldAmtCalming;
	int nTotalCM, nTotalEB, nTotalCalming;

	int nPayDebtAmt, nLoanAmt;
	int nFreeDOChance, nFreeEOChance;


	char strName[20];
	char strP1[20];
	char strP2[20];
	char strP3[20];
	char strP4[20];
	char strP5[20];
	char strP6[20];
	char strP7[20];
	char strP8[20];
	char strP9[20];
	char strP10[20];
	char strTemp[20];

	int nP1;
	int nP2;
	int nP3;
	int nP4;
	int nP5;
	int nP6;
	int nP7;
	int nP8;
	int nP9;
	int nP10;

	strName[0] = '\0';
	strP1[0] = '\0';
	strP2[0] = '\0';
	strP3[0] = '\0';
	strP3[0] = '\0';
	strP4[0] = '\0';
	strP5[0] = '\0';
	strP6[0] = '\0';
	strP7[0] = '\0';
	strP8[0] = '\0';
	strP9[0] = '\0';
	strP10[0] = '\0';
	strTemp[0] = '\0';

	nP1 = 0;
	nP2 = 0;
	nP3 = 0;
	nP4 = 0;
	nP5 = 0;
	nP6 = 0;
	nP7 = 0;
	nP8 = 0;
	nP9 = 0;
	nP10 = 0;

	bShowMenu = 1; //initally set to true until the user chooses to exit the game
	while(bShowMenu == 1)
	{
		displayStartMenu();
		scanf("%d", &nChoice);
   	    switch(nChoice)
   		 {
    		case 1:
    		{
    			nCash = STARTING_CASH;
				nLoan = STARTING_LOAN;
				nCity = 1;
				nLemonP = 0;
				nLavenderP = 0;
				nRosemaryP = 0;
				nMintP = 0;
				nCM = 0;
				nEB = 0;
				nCalming = 0;

    			nAveLemon = 0;
    			nAveLavender = 0;
    			nAveRosemary = 0;
    			nAveMint = 0;

    			nOldStockLemon = 0;
    			nOldStockLavender = 0;
    			nOldStockRosemary = 0;
    			nOldStockMint = 0;

    			nOldAveLemon = 0;
    			nOldAveLavender = 0;
    			nOldAveRosemary = 0;
    			nOldAveMint = 0;

    			nLemonSellPrice = 0;
    			nLavenderSellPrice = 0;
    			nRosemarySellPrice = 0;
    			nMintSellPrice = 0;

    			nAveCM = 0;
    			nAveEB = 0;
    			nAveCalming = 0;


    			/*repeats until one cycle is done*/
    			for(nDay = 1; nDay <= AMOUNT_DAYS; nDay++)
    			{

    				nDiffuserCharge = generateDiffuserCharge(nCity);

    				/*Generates random price within given range of essential oil per bottle*/
					nLemonBasePrice = getRandom(100, 150);
					nLavenderBasePrice = getRandom(20, 60);
					nRosemaryBasePrice = getRandom(70, 100);
					nMintBasePrice = getRandom(130, 200);

					/*Factors*/
					nLemonFactor = getRandom(102, 199);
					nLavenderFactor = getRandom(102, 199);
					nRosemaryFactor = getRandom(102, 199);
					nMintFactor = getRandom(102, 199);

					nLemonChance = getRandom(1, 100);
					nLavenderChance = getRandom(1, 100);
					nRosemaryChance = getRandom(1, 100);
					nMintChance = getRandom(1, 100);

					nFreeEOChance = getRandom(1, 100);
					nFreeDOChance = getRandom(1, 100);

					nLemonShop = computeFinalPrice(nLemonFactor, nLemonChance, nLemonBasePrice);
					nLavenderShop = computeFinalPrice(nLavenderFactor, nLavenderChance, nLavenderBasePrice);
					nRosemaryShop = computeFinalPrice(nRosemaryFactor, nRosemaryChance, nRosemaryBasePrice);
					nMintShop = computeFinalPrice(nMintFactor, nMintChance, nMintBasePrice);


					/*Generates random stock per bottle for each oil for the day if its available*/
					nLemonStock = generateStock(nLemonShop);
					nLavenderStock = generateStock(nLavenderShop);
					nRosemaryStock = generateStock(nRosemaryShop);
					nMintStock = generateStock(nMintShop);

					/*Assigns the latest selling price generated as selling price of oil*/
					if(nLemonShop >= 1)
					{
						nLemonSellPrice = nLemonShop;
					}

					if(nLavenderShop >= 1)
					{
						nLavenderSellPrice = nLavenderShop;
					}

					if(nRosemaryShop >= 1)
					{
						nRosemarySellPrice = nRosemaryShop;
					}

					if(nMintShop >= 1)
					{
						nMintSellPrice = nMintShop;
					}

					/*Generates back up inital sell price if a positive sell price was never generated */
					if(nLemonSellPrice == 0)
					{
						nLemonSellPrice = getRandom(100, 150);
					}

					if(nLavenderSellPrice == 0)
					{
						nLemonSellPrice = getRandom(20, 60);
					}

					if(nRosemarySellPrice == 0)
					{
						nRosemarySellPrice = getRandom(70, 100);
					}

					if(nMintSellPrice == 0)
					{
						nMintSellPrice = getRandom(130, 200);
					}

					/*Computes for the selling price of each diffuser oil (per bottle) for the day*/
					nCMPrice = computeCMPrice(nLemonSellPrice, nRosemarySellPrice, nMintSellPrice);
					nEBPrice = computeEBPrice(nLemonSellPrice, nRosemarySellPrice, nMintSellPrice);
					nCalmingPrice = computeCalmingPrice(nLemonSellPrice, nLavenderSellPrice, nRosemarySellPrice);

					if(nFreeEOChance >= 1 && nFreeEOChance <= 40)
					{
						getFreeEO(&nLemonP, &nRosemaryP, &nLavenderP, &nMintP);
					}

					if(nFreeDOChance >= 1 && nFreeDOChance <= 30)
					{
						getFreeDO(&nCM, &nEB, &nCalming);
					}

             		/*bRunMenu initially set to true so that the menu is continuously displayed until the user travels*/
					bRunMenu = 1;

					/*Displays menu, and allows user to do actions until user chooses to travel or until the 15th day is reached */
					while(bRunMenu == 1)
					{
						printf("\n\n");
						printf("Day %d ",nDay);
						displayCity(nCity);
						printf("Cash: $%d", nCash);
						printf("||Debt: $%d\n",nLoan);

						//PLAYER STOCK IN HAND
						printf("\n()()()()()()()()()()()()()()()()()()()() PLAYER STOCK-ON-HAND ()()()()()()()()()()()()()()()()()()()()()()()()()()()()\n");
						printf("\nEssential Oils             Stock-on-hand in drops        Average cost per drop\n");

						if(nLemonP < 1 && nLavenderP < 1 && nRosemaryP < 1 && nMintP < 1)
							printf("\n\n %60s","You have no essential oils in stock.");
						if(nLemonP > 0)
							printf("\n   Lemon %29d %29d\n",nLemonP, nAveLemon );
						if(nLavenderP > 0)
							printf("\n   Lavender %26d %29d\n", nLavenderP, nAveLavender);
						if(nRosemaryP > 0)
							printf("\n   Rosemary %26d %29d\n",nRosemaryP, nAveRosemary);
						if(nMintP > 0)
							printf("\n   Mint  %29d %29d\n",nMintP, nAveMint);

						printf("\n\n------------------------------------------------------------------------------------------------------------------\n");
						printf("Diffuser Oils               Stock-on-hand in bottles         Selling price per bottle       Average price per bottle   \n");

						if(nCM < 1 && nEB < 1 && nCalming < 1)
							printf("\n\n %60s","You have no diffuser oils in stock.\n\n");
						if(nCM > 0)
							printf("\nClear Minds    %25d %36d %25d\n",nCM, nCMPrice, nAveCM);
						if(nEB > 0)
							printf("\nEnergy Booster %25d %36d %25d\n",nEB, nEBPrice, nAveEB);
						if(nCalming > 0)
							printf("\nCalming        %25d %36d %25d\n",nCalming, nCalmingPrice, nAveCalming);



						//SHOP
						printf("\n-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.");
						printf("\n<><><><><><><><><><><><><><><><><><><><> SHOP <><><><><><><><><><><><><><><><><><><><>  \n");
						printf("-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.\n");
						printf("Essential Oils      Price per bottle      Price per drop       Stock in bottles\n");

						if(nLemonStock > 0)
							printf("\n   Lemon    %17d %20d %21d\n", nLemonShop, nLemonShop / 10, nLemonStock);
						if(nLavenderStock > 0)
							printf("\n   Lavender %17d %20d %21d\n", nLavenderShop, nLavenderShop / 10, nLavenderStock);
						if(nRosemaryStock > 0)
							printf("\n   Rosemary %17d %20d %21d\n", nRosemaryShop, nRosemaryShop / 10, nRosemaryStock);
						if(nMintStock > 0)
							printf("\n   Mint     %17d %20d %21d\n", nMintShop, nMintShop / 10, nMintStock);


						/**/
						printf("\nActions:\n");
						printf("[1] Buy\n");
						printf("[2] Sell\n");
						printf("[3] Make\n");
						printf("[4] Pay Debt\n");
						printf("[5] Loan\n");
						if(nDay != AMOUNT_DAYS)
							printf("[6] Travel\n");
						else
							printf("[6] End Trip\n");

						printf("\nPlease enter a number corresponding to the action you want to take: ");
						scanf("%d",&nAction);
						switch(nAction)
						{
							case 1:
							{
								displayEOChoices();

								nEOChoice = getEOChoice();

								if(nEOChoice == 1)
								{
									setPriceAndStock(&nBuyPrice, &nCurrentStock, nRosemaryShop, nRosemaryStock);
								}
								else if(nEOChoice == 2)
								{
									setPriceAndStock(&nBuyPrice, &nCurrentStock, nLavenderShop, nLavenderStock);
								}
								else if(nEOChoice == 3)
								{
									setPriceAndStock(&nBuyPrice, &nCurrentStock, nLemonShop, nLemonStock);
								}
								else if(nEOChoice == 4)
								{
									setPriceAndStock(&nBuyPrice, &nCurrentStock, nMintShop, nMintStock);
								}

								if(nEOChoice != 0)
								{
									nMaxBuyAmt = computeMaxBuyAmt(nCash, nBuyPrice, nCurrentStock);

									printf("You may enter [0] if you change your mind about buying.\n");
									printf("How many bottles would you like to buy? You can buy a maximum of %d bottles: ",nMaxBuyAmt);

									nBuyAmt = getBuyAmt(nMaxBuyAmt);

								}

								if(nBuyAmt != 0)
								{
									switch(nEOChoice)
									{
										case 1:
										{

											nAveRosemary = computeAveDrop(nOldStockRosemary, nOldAveRosemary, nBuyAmt, nRosemaryShop);


											nOldAveRosemary = nAveRosemary;

											nRosemaryStock = nRosemaryStock - nBuyAmt;
											nCash = nCash - nBuyAmt * nBuyPrice;
											nRosemaryP = (nRosemaryP + nBuyAmt * 10);

											nOldStockRosemary = nRosemaryP;


											break;
										}
										case 2:
										{
											nAveLavender = computeAveDrop(nOldStockLavender, nOldAveLavender, nBuyAmt, nLavenderShop);


											nOldAveLavender = nAveLavender;

											nLavenderStock = nLavenderStock - nBuyAmt;
											nCash = nCash - nBuyAmt * nBuyPrice;
											nLavenderP = (nLavenderP + nBuyAmt * 10);

											nOldStockLavender = nLavenderP;
											break;
										}
										case 3:
										{
											nAveLemon = computeAveDrop(nOldStockLemon, nOldAveLemon, nBuyAmt, nLemonShop);


											nOldAveLemon = nAveLemon;

											nLemonStock = nLemonStock - nBuyAmt;
											nCash = nCash - nBuyAmt * nBuyPrice;
											nLemonP = (nLemonP + nBuyAmt * 10);

											nOldStockLemon = nLemonP;
											break;
										}
										case 4:
										{
											nAveMint = computeAveDrop(nOldStockMint, nOldAveMint, nBuyAmt, nMintShop);


											nOldAveMint = nAveMint;

											nMintStock = nMintStock - nBuyAmt;
											nCash = nCash - nBuyAmt * nBuyPrice;
											nMintP = (nMintP + nBuyAmt * 10);

											nOldStockMint = nMintP;

											break;

										}
									}
								}

								resetBuyValues(&nBuyPrice, &nCurrentStock, &nMaxBuyAmt);


								break;
							}
							case 2:
							{


				    			printf("\n\n");
				  			    printf("+-+-+-+-+-+-+-+-+-+-+-+\n");
				  			    printf("[0] EXIT\n");
								printf("[1] Rosemary\n");
								printf("[2] Lavender\n");
								printf("[3] Lemon\n");
								printf("[4] Mint\n");
								printf("[5] Clear Minds\n");
								printf("[6] Energy Booster\n");
								printf("[7] Calming\n");
								printf("+-+-+-+-+-+-+-+-+-+-+-+\n");
								printf("Please enter the number corresponding to the oil you would like to sell: ");

								nSellChoice = getSellChoice();

								if(nSellChoice == 1)
		 						{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nRosemarySellPrice, nRosemaryP);

									nSellAmt = getSellAmt(nMaxSellAmt);
									sellEO(&nCash, &nRosemaryP, nSellAmt, nRosemarySellPrice);

								}
								else if(nSellChoice == 2)
								{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nLavenderSellPrice, nLavenderP);

									nSellAmt = getSellAmt(nMaxSellAmt);
									sellEO(&nCash, &nLavenderP, nSellAmt, nLavenderSellPrice);


								}
								else if (nSellChoice == 3)
								{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nLemonSellPrice, nLemonP);


									nSellAmt = getSellAmt(nMaxSellAmt);
									sellEO(&nCash, &nLemonP, nSellAmt, nLemonSellPrice);


								}
								else if (nSellChoice == 4)
								{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nMintSellPrice, nMintP);

									nSellAmt = getSellAmt(nMaxSellAmt);
									sellEO(&nCash, &nMintP, nSellAmt, nMintSellPrice);



								}
								else if(nSellChoice == 5)
								{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nCMPrice, nCM);

									nSellAmt = getSellAmt(nMaxSellAmt);
									sellDO(&nCash, &nCM, nSellAmt, nCMPrice);

								}
								else if(nSellChoice == 6)
								{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nEBPrice, nEB);

									nSellAmt = getSellAmt(nMaxSellAmt);
									sellDO(&nCash, &nEB, nSellAmt, nEBPrice);

								}
								else if(nSellChoice == 7)
								{
									nMaxSellAmt = get_display_MaxOilSell(nSellChoice, nCalmingPrice, nCalming);


									nSellAmt = getSellAmt(nMaxSellAmt);
									sellDO(&nCash, &nCalming, nSellAmt, nCalmingPrice);

								}


								break;
							}
							case 3:
							{
							    printf("\n\nProcess Plant Fee: %d$", nDiffuserCharge);
								printf("\nWhich diffuser oil would you like to make?\n");
								printf("[0] EXIT\n");

								if(nLemonP >= 3 && nRosemaryP >= 2 && nMintP >= 2)
									printf("[1] Clear Minds\n");
								if(nRosemaryP >= 1 && nMintP >= 1 && nLemonP >= 1)
									printf("[2] Energy Booster\n");
								if(nLavenderP >= 3 && nRosemaryP >= 2 && nLemonP >= 1)
									printf("[3] Calming\n");

								nDOChoice = getDOChoice(nLemonP, nLavenderP, nRosemaryP, nMintP, nCash, nDiffuserCharge);

								nMaxDOAmt = computeMaxDOAmt(nLemonP, nLavenderP, nRosemaryP, nMintP, nDOChoice);

								if(nDOChoice != 0)
								{
									printf("\n\nYou can make a maximum of %d bottles.\n", nMaxDOAmt);
									printf("Amount of bottles you want to make: ");

									nDOAmt = getDOAmt(nMaxDOAmt);

								}


								if(nDOChoice == 1)
								{

									nOldAmtCM = nCM; //holds old stock before stock on hand is updated

									makeCM(&nLemonP, &nRosemaryP, &nMintP, nDOAmt);
									nCash -= nDiffuserCharge;
									nCM += nDOAmt;

									getCMUsed(&nLemonUsed, &nRosemaryUsed, &nMintUsed, nDOAmt);
									nAveCM = nLemonUsed * nAveLemon + nRosemaryUsed * nAveRosemary + nMintUsed * nAveMint;
									nAveCM += nDiffuserCharge;
									nAveCM /= nDOAmt;

									nAveCM = (nOldAveCM * nOldAmtCM + nAveCM * nDOAmt) / nCM;

									nOldAveCM = nAveCM;

								}
								else if(nDOChoice == 2)
								{
									nOldAmtEB = nEB;

									makeEB(&nLemonP, &nMintP, &nRosemaryP, nDOAmt);
									nCash -= nDiffuserCharge;
									nEB += nDOAmt;

									getEBUsed(&nLemonUsed, &nMintUsed, &nRosemaryUsed, nDOAmt);
									nAveEB = nLemonUsed * nAveLemon + nMintUsed * nAveMint + nRosemaryUsed * nAveRosemary;
									nAveEB += nDiffuserCharge;
									nAveEB /= nDOAmt;

									nAveEB = (nOldAveEB * nOldAmtEB + nAveEB * nDOAmt) / nEB;

									nOldAveEB = nAveEB;
								}
								else if(nDOChoice == 3)
								{
									nOldAmtCalming = nCalming;

									makeCalming(&nLavenderP, &nRosemaryP, &nLemonP, nDOAmt);
									nCash -= nDiffuserCharge;
									nCalming += nDOAmt;

									getCalmingUsed(&nLavenderUsed, &nRosemaryUsed, &nLemonUsed, nDOAmt);
									nAveCalming = nLavenderUsed * nAveLavender + nRosemaryUsed * nAveRosemary + nLemonUsed * nAveLemon;
									nAveCalming += nDiffuserCharge;
									nAveCalming /= nDOAmt;

									nAveCalming = (nOldAveCalming * nOldAmtCalming + nAveCalming * nDOAmt) / nCalming;

									nOldAveCalming = nAveCalming;
								}

								break;
							}
							case 4:
							{

								nPayDebtAmt = getPayDebtAmt(nCash, nLoan);

								nLoan -= nPayDebtAmt;
								nCash -= nPayDebtAmt;

								break;
							}
							case 5:
							{
								nLoanAmt = getLoanAmt();

								nLoan += nLoanAmt;
								nCash += nLoanAmt;

								break;

							}
							case 6:
							{
								if(nDay != AMOUNT_DAYS)
								{
									displayCityChoices();

									/* Asks user for input repeatedly until the user enters a valid number*/
									nCity = getCity();

								}

								bRunMenu = 0;

								break;
							}
							default:
							{
								printf("Please enter a valid number.");

							}
						}
					}



    				/*Charges the user for the daily interest of unpaid loans after each day except for
					the last day and if the user has already paid all loans*/
    				if(nDay != AMOUNT_DAYS && nLoan > 0)
    				{
    					nCash -= nLoan * 0.10;

    					/*if player can't pay a portion of daily interest rate, that amount is added to debt*/
    					if(nCash < 0)
    					{
    						nLoan -= nCash;
    						nCash = 0;
						}

					}
					else if(nDay == AMOUNT_DAYS)
					{
						/*display final stats of the cycle */

						printf("\n\n\n\n\n");
						printf("Congrats, you finished a sales trip! Here's a summary of your final stats: \n\n");
						printf("=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=\n");
						printf("=.=.= Essential Oil =.=.=.=.=.= Drops Remaining =.=.=.=.=.=.=.=\n ");
						printf("=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=\n");
						printf("|                                                              |\n");
						printf("%14s %26d\n\n", "Lemon", nLemonP);
						printf("%14s %26d\n\n", "Rosemary", nRosemaryP);
						printf("%14s %26d\n\n", "Mint", nMintP);
						printf("%14s %26d\n\n", "Lavender", nLavenderP);
						printf("=.=.= Diffuser Oil =.=.=.=.=.=. Bottles Remaining =.=.=.=.=.=.=\n\n");
						printf("%14s %26d\n\n", "Clear Minds", nCM);
						printf("%14s %26d\n\n", "Energy Booster", nEB);
						printf("%14s %26d\n\n", "Calming", nCM);
						printf("---------------------------------------------------------------\n\n");
						printf("%14s %26d$\n\n", "CASH", nCash);
						printf("%14s %26d$\n\n", "DEBT", nLoan);
						printf("%14s %26d$", "CASH - DEBT", nCash - nLoan);

						nCash -= nLoan;

						if(nCash > nP1)
						{

							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP1);
							swapNum(&nCash, &nP2);
							swapNum(&nCash, &nP3);
							swapNum(&nCash, &nP4);
							swapNum(&nCash, &nP5);
							swapNum(&nCash, &nP6);
							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);



							strcpy(strTemp, strP1);
							strcpy(strP1, strName);
							strcpy(strName, strP2);
							strcpy(strP2, strTemp);
							strcpy(strTemp, strP3);
							strcpy(strP3, strName);
							strcpy(strName, strP4);
							strcpy(strP4, strTemp);
							strcpy(strTemp, strP5);
							strcpy(strP5, strName);
							strcpy(strName, strP6);
							strcpy(strP6, strTemp);
							strcpy(strTemp, strP7);
							strcpy(strP7, strName);
							strcpy(strName, strP8);
							strcpy(strP8, strTemp);
							strcpy(strTemp, strP9);
							strcpy(strP9, strName);
							strcpy(strName, strP10);
							strcpy(strP10, strTemp);

						}
						else if(nCash > nP2)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP2);
							swapNum(&nCash, &nP3);
							swapNum(&nCash, &nP4);
							swapNum(&nCash, &nP5);
							swapNum(&nCash, &nP6);
							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP2);
							strcpy(strP2, strName);
							strcpy(strName, strP3);
							strcpy(strP3, strTemp);
							strcpy(strTemp, strP4);
							strcpy(strP4, strName);
							strcpy(strName, strP5);
							strcpy(strP5, strTemp);
							strcpy(strTemp, strP6);
							strcpy(strP6, strName);
							strcpy(strName, strP7);
							strcpy(strP7, strTemp);
							strcpy(strTemp, strP8);
							strcpy(strP8, strName);
							strcpy(strName, strP9);
							strcpy(strP9, strTemp);
							strcpy(strTemp, strP10);
							strcpy(strP10, strName);

						}
						else if(nCash > nP3)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP3);
							swapNum(&nCash, &nP4);
							swapNum(&nCash, &nP5);
							swapNum(&nCash, &nP6);
							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP3);
							strcpy(strP3, strName);
							strcpy(strName, strP4);
							strcpy(strP4, strTemp);
							strcpy(strTemp, strP5);
							strcpy(strP5, strName);
							strcpy(strName, strP6);
							strcpy(strP6, strTemp);
							strcpy(strTemp, strP7);
							strcpy(strP7, strName);
							strcpy(strName, strP8);
							strcpy(strP8, strTemp);
							strcpy(strTemp, strP9);
							strcpy(strP9, strName);
							strcpy(strName, strP10);
							strcpy(strP10, strTemp);

						}
						else if(nCash > nP4)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP4);
							swapNum(&nCash, &nP5);
							swapNum(&nCash, &nP6);
							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP4);
							strcpy(strP4, strName);
							strcpy(strName, strP5);
							strcpy(strP5, strTemp);
							strcpy(strTemp, strP6);
							strcpy(strP6, strName);
							strcpy(strName, strP7);
							strcpy(strP7, strTemp);
							strcpy(strTemp, strP8);
							strcpy(strP8, strName);
							strcpy(strName, strP9);
							strcpy(strP9, strTemp);
							strcpy(strTemp, strP10);
							strcpy(strP10, strName);



						}
						else if(nCash > nP5)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP5);
							swapNum(&nCash, &nP6);
							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP5);
							strcpy(strP5, strName);
							strcpy(strName, strP6);
							strcpy(strP6, strTemp);
							strcpy(strTemp, strP7);
							strcpy(strP7, strName);
							strcpy(strName, strP8);
							strcpy(strP8, strTemp);
							strcpy(strTemp, strP9);
							strcpy(strP9, strName);
							strcpy(strName, strP10);
							strcpy(strP10, strTemp);

						}
						else if(nCash > nP6)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP6);
							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP6);
							strcpy(strP6, strName);
							strcpy(strName, strP7);
							strcpy(strP7, strTemp);
							strcpy(strTemp, strP8);
							strcpy(strP8, strName);
							strcpy(strName, strP9);
							strcpy(strP9, strTemp);
							strcpy(strTemp, strP10);
							strcpy(strP10, strName);


						}
						else if(nCash > nP7)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);


							swapNum(&nCash, &nP7);
							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP7);
							strcpy(strP7, strName);
							strcpy(strName, strP8);
							strcpy(strP8, strTemp);
							strcpy(strTemp, strP9);
							strcpy(strP9, strName);
							strcpy(strName, strP10);
							strcpy(strP10, strTemp);

						}
						else if(nCash > nP8)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP8);
							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP8);
							strcpy(strP8, strName);
							strcpy(strName, strP9);
							strcpy(strP9, strTemp);
							strcpy(strTemp, strP10);
							strcpy(strP10, strName);

						}
						else if(nCash > nP9)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP9);
							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP9);
							strcpy(strP9, strName);
							strcpy(strName, strP10);
							strcpy(strP10, strTemp);

						}
						else if(nCash > nP10)
						{
							printf("\n\nCongrats! You have a place in the top ten list.");
							printf("Please enter your name: ");

							/*used to clear input buffer from previous use of scanf() so that the user's name can be entered*/
							fflush(stdin);

							fgets(strName, 20, stdin);

							swapNum(&nCash, &nP10);

							strcpy(strTemp, strP10);
							strcpy(strP10, strName);
						}
					}

				}

    			break;

			}
			case 2:
			{
				printf("\n\n------------TOP TEN LIST-----------\n\n");

				printf("1. Player Name: %s\n   Cash: $%d\n\n",strP1, nP1);
				printf("2. Player Name: %s\n   Cash: $%d\n\n",strP2, nP2);
				printf("3. Player Name: %s\n   Cash: $%d\n\n",strP3, nP3);
				printf("4. Player Name: %s\n   Cash: $%d\n\n",strP4, nP4);
				printf("5. Player Name: %s\n   Cash: $%d\n\n",strP5, nP5);
				printf("6. Player Name: %s\n   Cash: $%d\n\n",strP6, nP6);
				printf("7. Player Name: %s\n   Cash: $%d\n\n",strP7, nP7);
				printf("8. Player Name: %s\n   Cash: $%d\n\n",strP8, nP8);
				printf("9. Player Name: %s\n   Cash: $%d\n\n",strP9, nP9);
				printf("10. Player Name: %s\n   Cash: $%d\n\n",strP10, nP10);

				break;
			}
			case 3:
			{
				bShowMenu = 0;
				break;
			}
			default:
			{
				printf("Please enter valid number!");


			}

		}
	}

	printf("\nThank you for playing!");
	return 0;

}
